#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start $daemon at boot time
# Description:       Enable service provided by $daemon.
### END INIT INFO

dir=""
user=""
cmd=""

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

. /lib/lsb/init-functions

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        log_action_msg "Already started"
    else
        log_daemon_msg "Starting $name"
	start-stop-daemon -p $pid_file -m -b -d $dir -x $dir$cmd --start
	log_end_msg $?
    fi
    ;;
    stop)
    if is_running; then
        log_daemon_msg "Stopping $name.."
	start-stop-daemon -p $pid_file --stop
        #kill `get_pid`
        #for i in {1..10}
        #do
        #    if ! is_running; then
        #        break
        #    fi

        #    echo -n "."
        #    sleep 1
        #done
        #echo

        #if is_running; then
        #    echo "Not stopped; may still be shutting down or shutdown may have failed"
        #    exit 1
        #else
        #    echo "Stopped"
        #    if [ -f "$pid_file" ]; then
        #        rm "$pid_file"
        #    fi
        #fi
	log_end_msg $?
    else
        log_warning_msg "Not running"
	log_end_msg 1
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        log_warning_msg "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        log_action_msg "Running"
    else
        log_action_msg "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
